name: Build Suporte Dktec

on:
  workflow_dispatch:
  push:
    tags:
      - "dktec-*"

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ github.ref_type == 'tag' && github.ref_name || 'dktec-nightly' }}
